### ISSUE TITLE
How is this project deployed?

### ISSUE THREAD

**Issue by CliveUnger** [statsfm/statsfm.js#7]
I am curious about the infrastructure for this project. I saw that the web frontend uses Next.js. Is this also deployed that way? How is the data stored?

**Comment by stijnvdkolk** [comment]
For the website, we indeed use Next.js, and we are running this in a cluster, you can find a Dockerfile in that repository, which is the one we use for deployment of the website. We are unable to answer any questions based on how we store data internally.
